config/routes.rb
SiteScrapping::Application.routes.draw do
  resources :scrapping
   root 'profile_informations#index'

  

end

app/models/scrapper.rb
class Scrapper

  def self.make_absolute( href, root )
    URI.parse(root).merge(URI.parse(href)).to_s
  end

  # check the specifc site folder exists If it's reuse or else create the new directory with that url name
  def self.check_folder_exists_and_create name
    folder_exists = Dir.exists?("#{Rails.root}/app/assets/images/#{name}")
    Dir.mkdir("#{Rails.root}/app/assets/images/#{name}") if !folder_exists
    return folder_exists
  end


  def self.fetch_images_from_directory dir_name
    @image_files = Dir.entries("#{Rails.root}/app/assets/images/#{dir_name}").map{|name|  "#{dir_name}/#{name}"}
    return  @image_files
  end

  def self.download_images folder_name, url, index
    extn = url.split('.').last || "jpg"
    file_name = "img#{index+1}.#{extn}"
    File.open(File.join(Rails.root, 'app', 'assets', 'images',folder_name, File.basename(file_name)),'wb'){ |f|
      f.write(open(url).read)
    }
    return folder_name+'/'+ File.basename(file_name)
  end


  def self.fetch_data params
    folder_name = URI.parse(params[:search_url]).host.gsub(/www\./, '').gsub('.', '_')
    check_folder_exists_and_create folder_name
    content_data = {}
    #debugger
    begin
      site_info = Nokogiri::HTML(open(params[:search_url]))
      content_data[:title] = site_info.css("title")[0].text
      if params[:page].present?
        images = fetch_images_from_directory folder_name
      else
        images = []
        site_info.xpath("//img/@src").each_with_index do |src, index|
          uri = make_absolute(src,params[:search_url])
          begin
            image_data = download_images folder_name, uri, index
            images.push image_data
          rescue
            next
          end

        end
      end
    rescue  RuntimeError,SocketError => error_msg
      error_msg = error_message_notifier(error_msg.class)
    end

    @images = images.present? ?  Kaminari.paginate_array(images).page(params[:page]).per(PER_PAGE) : error_msg
    return @images,content_data
  end

  def self.error_message_notifier type
   error_hash = Hash[SocketError,"Entered Web URL is not available...",RuntimeError,"Problem with connecting the Remote site..."]
   error_msg =  error_hash[type].present? ? error_hash[type] : "Problem with Fetching Images"
   return error_msg
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profile_informations_controller.rb
class ProfileInformationsController < ApplicationController
  def index

  end
end

app/controllers/scrapping_controller.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'
require 'uri'

class ScrappingController < ApplicationController

  # Method for scrapping information from the given site by the user
  def index
    @images, @site_content = Scrapper.fetch_data params if params[:search_url].present?
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def resource_params
    params.require(:search_data).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_informations_helper.rb
module ProfileInformationsHelper
end

app/helpers/scrapping_helper.rb
module ScrappingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "SiteScrapping" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">My Techno Spot........ </a>
      <div class="container-fluid nav-collapse">
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav" style="min-height: 964px;">
        <ul class="nav nav-list">
          <li class="nav-header"><%= link_to "Vel Pradeep.MS", "https://www.linkedin.com/in/velpradeep"  %></li>
          <%= image_tag("velpradeep1.JPG")%>
          <li>Ruby On Rails Developer</li>
          <li></li>
        </ul>
        <ul class="nav nav-list">

          <li><%= link_to "LinkedIn", "https://www.linkedin.com/in/velpradeep"  %></li>
          <li><%= link_to "Github", "https://github.com/velpradeep"  %></li>
          <li><%= link_to "Github Page", "https://velpradeep.github.io"  %></li>
          <li><%= link_to "stackoverflow", "http://stackoverflow.com/users/2341740/vel-pradeep"  %></li>
          <li>Mail:velrangitham.ms@gmail.com</li>
        </ul>

      </div><!--/.well -->

    </div><!--/span-->

    <div class="span9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>


  </div><!--/row-->
  <footer>

    <p style="text-align: center">&copy; Copyrights by PRADEEP KUMAR.MS, E-Mail: velrangitham.ms@gmail.com</p>

  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/profile_informations/index.html.erb
<div class="container-fluid">
  My Functional Experiments
  <div class="contents">
    <ul>
      <li><%= link_to("Image Scrapping", scrapping_index_path) %></li>
    </ul>
  </div>
</div>

app/views/scrapping/_site_images.html.erb
<h1 class="header" style="display: none">Scrapped Content</h1>
<div id="site_content_info">
<h2 class="site_title ">
  <%= @site_content[:title] if @site_content.present? %>
</h2>

</div>

<% if @images.present?%>
    <% @images.each do |img| %>
        <%= image_tag "#{img}" , :class => "img-responsive img-rounded" %>
    <%end%>
    <%= paginate @images if @images %>
<%end%>

app/views/scrapping/index.html.erb
<h1>Image Scrapping</h1>
<div class="ajax-loader" style="top:15px;"></div>
<%= form_tag scrapping_index_path, :method => "get", :html => { :class => 'navbar-form navbar-search pull-left search_form'},remote: true  do |f| %>
    <%= url_field_tag 'search_url','' , placeholder:"URL Starts With http:// or https://", class: "search-query"%>
    <%= button_tag "Submit", :id => "submit_url",:data => { :disable_with =>  "Please wait..." }, :class => "btn" %>

<%end%>

<div id="paginate_data">
  <%= render partial: "site_images" %>
</div>

<%= javascript_include_tag 'scrapping.js' %>

app/views/scrapping/index.js.erb
<% if @images.is_a?(Array)%>
$("#paginate_data").html("<%= escape_javascript( render(:partial => "site_images", locals: {images: @images,site_content: @site_content}) ) %>");
$(".header").prop('display', 'block');
$(".site_title").html("<%= @site_content[:title] if @site_content %>");

<%else%>
$(".header").prop('display', 'block');
$(".site_title").html("<%= @images %>");

<%end%>